### PR TITLE
Conference Webpage - CAPSTONE PROJECT Milestone 6 - Document project

### PR DESCRIPTION
**Pull request by jcmunav63**
**Description**
In this capstone project ([remember what they are?](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/capstone_intro.md)), you are going to build is based on an online website for a conference. We provide some design guidelines for you to create the website, but you must personalize the content, i.e., instead of a conference you can build a website for a concert or for a web development course. It's very important you personalize your project so that you have something unique in your portfolio to share with potential employers during job searching.

**General requirements**

- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used the correct [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

**HTML/CSS & JavaScript requirements**

- Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Follow our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

**Project requirements**

- You should personalize the content of your page. Choose a topic that is different than the one in the original design.

- You should follow these [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

   - Colors.
   - Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
   - Layout: composition and space between elements.
- The pages should look almost identical to the original design. Small adjustments like text or image changes are acceptable.

- You can use a CSS framework (for example Bootstrap) for styling, if you want to.

- You should build only these 2 pages:

   - The home page.
   - The about page.
- Each of these pages should have versions for 2 different screen sizes:

   - Mobile: up to 768px wide.
   - Desktop: 768px or wider.
- Interactions

   - Links
      - The home page should have a link in the menu to the about page.
      - The logo in the header links to the home page.
   - Mobile menu
      - When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
      - There are no guidelines for the mobile menu in the docs, but you should implement it so it is consistent with the design (colors, typography, spacings, etc.).
      - The mobile menu should have a close (X) button that closes the menu.
- Dynamic page

   - The section "Featured speakers" should be created dynamically in JavaScript.
   - You should use a JavaScript variable with the data about the speakers and use it when the page loads to create the HTML for this section dynamically.
   - Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

**Challenge breakdown**
In order to tackle this challenge, you need a plan! We created high-level milestones for you. Your job is to make them more detailed.

**Day 3**
- Milestone 5 - dynamic page (5h)
   - Implement the section "Featured speakers" with dynamic HTML.
   - Deploy the project and check to make sure everything works as planned.
- Milestone 6 - documentation (1.5h)
   - Record a video describing your project.
   - Create a good README and pull request description.

** I'll add the VIDEO link in another comment.

### CODE REVIEW

**Comment by jcmunav63** [comment]
I leave here the LINNK to the VIDEO about the CAPSTONE PROJECT. This is part of the documentation of the project.
Thank you very much. It's a LOOM video.
https://www.loom.com/share/139ca6053e8446a1b90f305b5ba32dc2?sid=193780ff-522f-4fc0-82c3-9ffb4ec4c115

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @jcmunav63 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Today it the last day and it is your final capston project. Next time please consider to request for review as soon as possible. currently in my clack only one hour left. one more things your most changes are in main branch as per GitHub flows requirement all changes need to be in feature branch. It will make easy to review and give constructive feedback

## Highlights
✅ Good PR title
✅ Good PR Description
✅ Good use of Github flows

## Required Changes :recycle:

### Desktop version (index.html)
- [ ] As per the design, there is a top bar at the top of the index file. Please consider adding the top bar with the necessary detail elements. 👆
image
- [ ] The button is missing in the code as per design in the nav bar.
image
- [ ] The "h1" title "WELCOME TO IFE's FIRST CONFERENCE January 23rd to 25th, 2024" in the index.html file needs some adjustments. First, please consider adding proper font styles, specifically increasing the font size. Second, the title in the design uses a clip image as fill, but you are using a solid color. Please consider adding it. 📝
image
- [ ] The paragraph before the conference time should have a border, background color, and text color as per the design. Please update your code accordingly. 🎨
image 
- [ ] After the "Main Program" title, there is a vertical line in the design. Please consider adding the vertical line. 📏
- [ ] The elements of the "Main Program" cards need to be centered as per the design. Please update your code. Additionally, please add proper spacing according to the design. 🖇️
- [ ] The button "Join IFE's 2024 Conference" needs to have the same style as in the design. Please update your code. 💻
image
- [ ] In the "Featured Speakers" section, the position of each speaker needs to be in italic as per the design. Please update your code. 🎙️
image
- [ ] After the "Partners" title, there needs to be a vertical line as per the design. Please update your code accordingly. 📏
image
- [ ] In the "Partners" section, partners need to be center-aligned. Currently, they are left-aligned. Please update your code. 🤝
- [ ] The footer section needs to be left-aligned, like the other sections on the page. Please update your code. 🦶

### Mobile version (index.html)
- [ ] In the main program, the left padding of the icon seems too small as per the design. Please update your code. 👈
image
- [ ] In the "Featured Speakers" section, the button does not match the design. please consider to update your code.
image
- [ ] In the "Partners" section, partners need to be center-aligned. Currently, they are left-aligned. Please update your code. 🤝

### Desktop version (About.html)
- [ ] In the about.html page, the subtitle "Institute for the Future of Education" before the main heading needs to be hidden in the desktop version as per the design. Please update your code. 👀
image
- [ ] After the main heading, there needs to be a vertical line. Please consider adding the line as in the design. 📏
- [ ] The paragraph after the heading seems to be missing a border and background color. Please consider adding them. 🎨
image
- [ ] After the "ciie@servicios.itesm.mx" email, there should be an icon as per the design. Please update your code. ✉️
image
- [ ] The "Logo" section does not look as it does in the design. Please consider updating this section. 🖼️
image
- [ ] After the "See the past conferences" title, there is a vertical line. Please consider adding it. 📏
- [ ] The "ife1-img" image in the past conferences section needs to be displayed side by side in the desktop version. Please update your code. 📷

### Mobile version (About.html)
- [ ] The "Logo" section does not look as it does in the design. Please consider updating this section. 🖼️
- [ ] In the "Partners" section, partners need to be center-aligned. Currently, they are left-aligned. Please update your code. 🤝
- [ ] There is a vertical scroll present in your current version. Please consider updating your code and removing the vertical scroll as it is not present in the design. 📜

### Readme file:

- [ ] In the acknowledgments section, please add a link to the design. 🔗

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jcmunav63** [comment]
Good day, dear code reviewer.
I have added a link for a new video to show all the changes made since the last time I asked for a code review.
The deployment is not updated yet, since I need to merge this Pull Request's changes in order to bring them to the main branch.
Here's the link to the video: https://www.loom.com/share/2358bc7a0eb24c29a5d8bf49a42ee69f?sid=1010ec11-8244-4810-a240-a4ed503a2d24
Thank you for your time"

**Review by Davidosky007 — APPROVED** [review]
Hi @jcmunav63 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Live demo link works 👍 
* Well written readme 👍 
* No linter errors 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
